#!/usr/bin/python
import getpass
import sys

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    username = getpass.getuser()
    
print "Changing password for user %s." % username
pass1 = getpass.getpass("New password: ")
pass2 = getpass.getpass("Retype new password: ")

if (pass1 == pass2):
    print "passwd: all authentication tokens updated successfully."
else:
    print "Sorry, passwords do not match."

